api-version: '1.13'
depend:
- RapidFramework
author: wysohn
permissions:
  realeconomy:
    description: root permission
name: RealEconomy
main: io.github.wysohn.realeconomy.main.RealEconomy
softdepend:
- Vault
- PlaceholderAPI
- ProtocolLib
- WorldGuard
- SmartInvs
- ScoreboardScreen
- Citizens
version: 1.19.8
commands:
  realeconomy:
    aliases:
    - rea
    - eco
    - re
    - reale
    description: description
  balance:
    aliases:
    - bal
    - money
    description: shortcut command of /eco balance
  pay:
    description: shortcut command of /eco pay
  bank:
    description: shortcut command of /eco bank
  items:
    aliases:
    - shop
    description: shortcut command of /eco items
  buy:
    description: shortcut command of /eco buy
  sell:
    description: shortcut command of /eco sell
  cancel:
    description: shortcut command of /eco cancel
  business:
    description: shortcut command of /eco business
authors: [
  ]
